### ISSUE TITLE
[Bug] mod incompat with bedrockify

### ISSUE THREAD

**Issue by DioEgizio** [W-OVERFLOW/Debugify#76]
**Describe the bug**
mod incompat with bedrockify

**To Reproduce**
install both bedrockify and debugify

**Expected behavior**
working

**Desktop (please complete the following information):**
 - Minecraft Version: `1.18.2`
 - Mod Loader: `Quilt Loader 0.16.0-beta.7`
 - Mod Version: `1.9.0`

**Additional context**
https://0x0.st/oTih.txt

**Checklist**
- [X] I made sure this bug hasn't already been reported
- [X] I made sure I am using the most up to date mod loader and mod version

**Comment by Wyvest** [comment]
That look more like a EvergreenHUD crash rather than a Debugify crash... Can you try without evergreenhud?

**Comment by DioEgizio** [comment]
Opz i uploaded the evergreenhud crash, my fault

**Comment by DioEgizio** [comment]
now i uploaded the right one

**Comment by Wyvest** [comment]
> now i uploaded the right one

This seems to be an issue from BedrockIfy instead of Debugify. In [here](https://github.com/juancarloscp52/BedrockIfy/blob/1.18.x/src/main/java/me/juancarloscp52/bedrockify/mixin/client/features/screenSafeArea/InGameHudMixin.java#L191-L195), it uses a Redirect instead of a ModifyArg(s) for no reason, which causes issues with Debugify which also redirects it (with a reason)

**Comment by Wyvest** [comment]
(you should probably report the to the original creator as well)

**Comment by DioEgizio** [comment]
Oh, I'm going to report to them.
Thanks for the help
