### ISSUE TITLE
[Bug] Item tooltips still not visible in some cases

### ISSUE THREAD

**Issue by Disketaa** [W-OVERFLOW/Debugify#86]
### Bug Description

![image](https://user-images.githubusercontent.com/76956762/167288250-72a44b49-6008-49b3-bdf4-1fcb20b8790b.png)

Greetings! Some big tooltips anyways get out of screen. Would be cool if you can reproduce something similar that ToolTipFix mod does. 

### Version

1.10.0

### Mod Loader Version

1.18.2, 0.14.4

### Mod Loader

Fabric

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment]
If you prefer tooltip fix, use tooltip fix. Debugify aims to fix the issue with parity for bedrock.

**Comment by Disketaa** [comment]
I primarily aims that in some cases tooltips still out of the screen

**Comment by RaptaG** [comment]
> If you prefer tooltip fix, use tooltip fix. Debugify aims to fix the issue with parity for bedrock.

Well, whether Debugify aims to fix this bug with a BE parity way, the bug remains without a fix, since "Large Item ToolTips" continue to "get cut off the screen". My opinion is that this bug should take a second look and be fixed this time, because it's pointless to include a bug which is not fixed. This could also annoy the user and make them go away from Debugify and/or modpacks that include it. I hope that what I said will be considered and I really hope to replace ToolTipFix with Debugify<br />sometime soon!
